language: ruby
dist: xenial
os: linux

before_install:
  # See https://github.com/travis-ci/travis-ci/issues/5861
  - gem update --system
  - gem install bundler
  - gem update bundler

bundler_args: --without development


stages:
  - name: "test"

jobs:
  include:
    - stage: "test"
      name: 'Ruby 2.4.4'
      rvm: '2.4.4'
      script: bundle exec rspec
    - name: 'Ruby 2.5.1'
      rvm: '2.5.1'
      script: bundle exec rspec
    - name: 'Ruby 2.6.3'
      rvm: '2.6.3'
      script: bundle exec rspec
    - name: 'Ruby JRuby'
      rvm: 'jruby-head'
      env: JRUBY_OPTS="--server -J-Xms1500m -J-Xmx1500m -J-XX:+UseConcMarkSweepGC -J-XX:-UseGCOverheadLimit -J-XX:+CMSClassUnloadingEnabled"
      jdk: oraclejdk11
      script: bundle exec rspec

