name: Tests

on:
  push:
  workflow_dispatch:

jobs:
  tests:
    name: Integration and Unit tests
    runs-on: ubuntu-latest
    env:
      CXX: 'g++-4.8'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Ruby 2.5.x
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.5
      - name: Build and run tests for Ruby 2.5.x
        run: |
          gem update --system
          gem install bundler
          gem update bundler
          bundle install --without development
          bundle exec rspec
      - name: Setup Ruby 2.6.x
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6
      - name: Build and run tests for Ruby 2.6.x
        run: |
          gem update --system
          gem install bundler
          gem update bundler
          bundle install --without development
          bundle exec rspec
      - name: Setup Ruby 2.7.x
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7
      - name: Build and run tests for Ruby 2.7.x
        run: |
          gem update --system
          gem install bundler
          gem update bundler
          bundle install --without development
          bundle exec rspec
  acceptance:
    name: Acceptance tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      - name: Checkout mock-server action
        uses: actions/checkout@v2
        with:
          repository: pubnub/client-engineering-deployment-tools
          ref: github-actions
          token: ${{ secrets.GH_TOKEN }}
          path: client-engineering-deployment-tools
      - name: Run mock server action
        uses: ./client-engineering-deployment-tools/actions/mock-server
        with:
          token: ${{ secrets.GH_TOKEN }}
      - name: Install dependencies
        run: |
          sudo gem install bundler &&
          bundle install
      - name: Run acceptance tests (optional)
        run: bundle exec cucumber sdk-specifications/features/ -p mock -p run_beta -p report_beta -f pretty
        continue-on-error: true
      - name: Run acceptance tests (required)
        run: bundle exec cucumber sdk-specifications/features/ -p mock -p run_main -p report_main -f pretty
      - name: Combine test results
        if: always()
        run: |
          sudo npm install -g junit-report-merger &&
          jrm ./main.xml "./main/**/*.xml" &&
          jrm ./beta.xml "./beta/**/*.xml"
      - name: Expose main report
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: acceptance-test-reports
          path: |
            main.xml
            beta.xml
          retention-days: 7
